- hosts: omehosts
  name: OMEnterprise Jobs
  gather_facts: False

  tasks:

  - name: Define output file
    include: set_output_file.yml type=DiscoveryJobs

  - name: Get Discovery Jobs
    local_action: >
      ome category=Discovery command=ShowJobs omeip={{ omeip }}
      omeuser={{ omeuser }} omepswd={{ omepswd }}
    register: result

  - name: Copy Jobs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
